### ISSUE TITLE
User search history functionality

### ISSUE THREAD

**Issue by kevinvongmany** [kevinvongmany/beatbrowser#4]
> AS A user clicking on an empty searchbar
> I WANT to be presented with search history as a drop-down list
> SO THAT I can quickly see something I searched for in the past

**Comment by kevinvongmany** [comment]
@leontran44 
Hey Leon,

To get started, your end goal should be to create a JS function that puts a localstorage array into a input box dropdown menu when selected. If you create an array of sample values and figure out how to save it to localStorage then that should be a good first step.

If you can get that working, I want you to figure out how to store each of those array values into a dropdown list of an input box, so we can plug that into Adriana's code later.

You'll also need to think about how to dynamically ADD values to your localStorage array.

**Comment by leontran44** [comment]
@kevinvongmany 
Thanks for the instruction, Kevin.

This flow is helping me a lot in understand it clearly what I need to do.
